@startmindmap
+ Расчет
++ Python ubuntu
+++ Синхронный запуск (последовательный запуск запросов подряд)
++++ select bill from accounts where char_length(name) = 5
++++ ...
++++ ...
+++ Асинхронный запуск (запуск каждого запроса в корутине)
++++ ...
+++ Thread Pool (запуск каждого запроса в отдельном треде)
++++ ...
+++ Process Pool (запуск каждого запроса в отдельном процессе)
++++ ...
++ Python alpine
+++ ...
++ PyPy
+++ ...
++ Python Nogil
+++ ...
-- Python ubuntu
--- Синхронный запуск (последовательный запуск запросов подряд)
---- select sum(bill) from accounts where char_length(name) = 5
---- ...
---- ...
--- Асинхронный запуск (запуск каждого запроса в корутине)
---- ...
--- Thread Pool (запуск каждого запроса в отдельном треде)
---- ...
--- Process Pool (запуск каждого запроса в отдельном процессе)
---- ...
-- Python alpine
--- ...
-- PyPy
--- ...
-- Python Nogil
--- ...
@endmindmap
